version: '3'

services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: SIGE_DOCS
    ports:
      - 8009:8009
    volumes:
      - ./:/docs/
    stdin_open: true
    tty: true
    command:
      ['serve', "--dev-addr=0.0.0.0:8009"]
