# Project information
site_name: "MEC-Energia Documentação"
site_description: "MEC-Energia"
site_author: "Lappis - UnB"
site_url: "https://lappis-unb.gitlab.io/projects/mec-energia/documentacao"

# Repository
repo_name: "documentacao"
repo_url: "https://lappis-unb.gitlab.io/projects/mec-energia/documentacao"

# Copyright
copyright: "Copyright &copy; Lappis-UnB"

# Theme settings
theme:
  name: readthedocs
  collapse_by_default: false
  highlightjs: true
  logo: 'assets/images/logo_mepa_nome.svg'
  favicon: 'assets/images/logo_mepa_cor.svg'
  language: "pt_BR"

# Content Menu
nav:
  - MEC-Energia: index.md
  - Arquitetura:
    - Introdução: "arquitetura/introducao.md"
    - Arquitetura: "arquitetura/arquitetura.md"
    - Casos de Uso: "arquitetura/casos_de_uso.md"
  - Repositórios: repositorios.md
  - Manual:
    - Usuário Operacional da Universidade: "manual/operacional_universidade.md"
    - Usuário Administrador da Universidade: "manual/admin_universidade.md"
    - Usuário Administrador do Sistema: "manual/sys_admin.md"

# Style
# extra_css:
#   - assets/style/extra.css

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta